# Generated by Django 5.1.7 on 2025-03-20 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_date_created_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación'),
        ),
    ]
